#ifndef ERROR_H
#define ERROR_H

typedef enum Outcome {
    OUTCOME_OK = 1,
    OUTCOME_ALLOCATION_FAILED,
    OUTCOME_INVALID_ARGS,

    OUTCOME_MATRIX_INVALID_SIZE,
    OUTCOME_OUT_OF_BOUNDS,

    OUTCOME_LAYER_UNKNOWN,
    OUTCOME_OPT_UNKNOWN,

    OUTCOME_FILE_VERSION_MISMATCH,
    OUTCOME_FILE_INVALID,
    OUTCOME_FILE_CREATE_FAILED,
    OUTCOME_FILE_OPEN_FAILED,
    OUTCOME_FILE_READ_FAILED,
    OUTCOME_FILE_WRITE_FAILED,
} Outcome;

#endif /* ERROR_H */
